version: '3'
services:
  database:
    image: postgres:15.1-alpine3.17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - storage:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  storage:
