name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      SECRET_KEY: yzbz$ux+$om*9%!2yl1o6$%!_8d1y8!olb4bjc34li(!m6s#yo
      DEBUG: True
      ALLOWED_HOSTS: 127.0.0.1,localhost,0.0.0.0
      DATABASE_URL: postgres://postgres:postgres@0.0.0.0:5432/postgres

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11.1
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1

      - uses: abatilo/actions-poetry@v2

      - name: Config python version
        run: |
          poetry env use 3.11.1
      - name: Installing the dependencies
        run: |
          poetry install
          # poetry export -f requirements.txt --without-hashes --with dev --output requirements.txt
          # pip install -r requirements.txt
      - name: Run makemigrations
        run: |
          poetry run python manage.py makemigrations
      - name: Run Test
        run: |
          poetry run python manage.py test
